import com.provia.bemt.domain.*

class Surveydata {

	def load() {
		println "Surveydata.groovy: creating survey enumeration data"		

    //SurveyInstitutionType
		println "Surveydata.groovy: SurveyInstitutionType"		
    def svy = new SurveyInstitutionType(name: "Academic Medical Center").save(flush:true, failOnError:true)
    svy = new SurveyInstitutionType(name: "Community Based Hospital").save(flush:true, failOnError:true)
    svy = new SurveyInstitutionType(name: "Government Program").save(flush:true, failOnError:true)
    svy = new SurveyInstitutionType(name: "Independent Research Laboratory").save(flush:true, failOnError:true)
    svy = new SurveyInstitutionType(name: "Commercial entity").save(flush:true, failOnError:true)

    //SurveyCountry
		println "Surveydata.groovy: SurveyCountry"		
    svy = new SurveyCountry(name: "United States").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Australia").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Argentina").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Belgium").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Brazil").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Canada").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "China").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Croatia").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Finland").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "France").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Germany").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Hungary").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "India").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Iran, Islamic Republic of").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Ireland").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Israel").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Italy").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Japan").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Jordan").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Lithuania").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Luxembourg").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Malaysia").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Netherlands").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "New Zealand").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Nigeria").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Norway").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Poland").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Portugal").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Saudi Arabia").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Singapore").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "Spain").save(flush:true, failOnError:true)
    svy = new SurveyCountry(name: "United Kingdom").save(flush:true, failOnError:true)

    //SurveyGeoArea
		println "Surveydata.groovy: SurveyGeoArea"		    
    svy = new SurveyGeoArea(name: "Urban").save(flush:true, failOnError:true)
    svy = new SurveyGeoArea(name: "Rural").save(flush:true, failOnError:true)

    //SurveyOperatingModel
		println "Surveydata.groovy: SurveyOperatingModel"		
    svy = new SurveyOperatingModel(name: "Centralized").save(flush:true, failOnError:true) 
    svy = new SurveyOperatingModel(name: "Federated").save(flush:true, failOnError:true)
    svy = new SurveyOperatingModel(name: "Networked").save(flush:true, failOnError:true) 
    svy = new SurveyOperatingModel(name: "Independent").save(flush:true, failOnError:true)

    //SurveyFacility
		println "Surveydata.groovy: SurveyFacility"		
    svy = new SurveyFacility(name: "<2000 ft²").save(flush:true, failOnError:true)
    svy = new SurveyFacility(name: "2,001 to 5,000 ft²").save(flush:true, failOnError:true)
    svy = new SurveyFacility(name: "15,001 to 50,000 ft²").save(flush:true, failOnError:true)
    svy = new SurveyFacility(name: "5,001 to 15,000 ft²").save(flush:true, failOnError:true)
    svy = new SurveyFacility(name: "50,001 to 100,000 ft²").save(flush:true, failOnError:true)
    svy = new SurveyFacility(name: ">100,000 ft²").save(flush:true, failOnError:true)

    //SurveyExpRecovery
		println "Surveydata.groovy: SurveyExpRecovery"		
    svy = new SurveyExpRecovery(name: "26%-50%").save(flush:true, failOnError:true)
    svy = new SurveyExpRecovery(name: "76%-100%").save(flush:true, failOnError:true)
    svy = new SurveyExpRecovery(name: "1%-25%").save(flush:true, failOnError:true)
    svy = new SurveyExpRecovery(name: "51%-75%").save(flush:true, failOnError:true)
    svy = new SurveyExpRecovery(name: "0%").save(flush:true, failOnError:true)
    svy = new SurveyExpRecovery(name: "> 100%").save(flush:true, failOnError:true)

    //SurveyServiceType 
		println "Surveydata.groovy: SurveyServiceType"		
    svy = new SurveyServiceType(name: "Biobanking project/protocol consultation").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biospecimen protocol and/or consent writing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biospecimen protocol regulatory submission").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biospecimen procedure/SOP writing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biobank technical support, in-or out-sourced").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Return of biospecimen research results to study participants and/or specimen donors").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Sample collection inventory management").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Sample storage and monitoring").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biobank inventory management database quality/best practice review audit").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Sample collection inventory management quality/best practice review audit").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Sample collection inventory management, transfer and/or relocation").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Sample collection inventory management, culling").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Sample collection inventory management, disaster recovery").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Specimen transport").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Annual biospecimen/project collection report").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Study cohort selection").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Specimen shipping & handling costs, flat fee (does not include shipping fees)").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Education and training").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: DNA extraction from 1 to 5 mls whole blood").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "RNA integrity number (RIN) testing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Pathology case review for clinical diagnosis and morphological confirmation").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Copy of pathology report").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Specimen biosketch report").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biospecimen inventory management database consultation").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Specimen collection kit assembly and shipping").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biospecimen proficiency testing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biobank consumable/supply ordering support").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biospecimen proficiency testing (sample set)").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Immunohistochemistry (IHC) testing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Gene expression profiling (DNA, RNA, protein)").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Pathology external consult, case review").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Evaluating and/or consenting donors for specimen and/or data collection").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Chart extraction").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Genetic testing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Post mortem brain tissue retrieval and handling").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Label printing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Specimen aliquotting").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Vial relabeling").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Biobank project/protocol consultation").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Extraction of DNA/RNA, each").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Serum/plasma processing, each").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Establishment of cell lines from skin, each").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Establishment of cell lines from muscle, each").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Distribution, flat fee").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Distribution myoblast cell line, each").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Packaging specimen shipments (flat fee, does not include additional shipping fees)").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: DNA/RNA concentration/purity testing by spectrophotometry").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Automated DNA/RNA extraction from batch samples").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: DNA Integrity testing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Biospecimen protocol and/or consent writing, including SOPs").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Sample storage and monitoring, annually per shelf").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "SNP genotyping").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "DNA sequencing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "In-situ hybridization (ISH) testing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "RNA sequencing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Mass spectrometry 2-D protein profiling").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Mass spectrometry protein profiling, isotope tagging method").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Protein microarrays ('Protein chip')").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Genetic testing, flat fee").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Education and training, flat fee").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Microsatellite fingerprinting").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Karyotyping").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: dsDNA quantity determination").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Document management (E.g. CDA/contracts, MTA/IRB)").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Invoicing and packing").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Equipment/Supply use").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Auxiliary staff support").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Laboratory use").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Equipment use").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: Supply use").save(flush:true, failOnError:true)
    svy = new SurveyServiceType(name: "Other: DNA extraction").save(flush:true, failOnError:true)

    //SurveyProductType
		println "Surveydata.groovy: SurveyProductType"		
    svy = new SurveyProductType(name: "Serum").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Plasma").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Urine").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Cerebrospinal fluid (CSF)").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "PBMC's").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "RNA, blood").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Whole blood").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "DNA, blood").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Tumor tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Normal tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Tumor tissue FFPE block").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Normal tissue FFPE block").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Tumor TMA block").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "H&E slide, tumor tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Buffy coat").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "DNA, tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "RNA, tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Blood spot card").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Sperm").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Saliva").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Buccal cells").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Stool").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Toenails").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Hair").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Tumor and adjacent normal tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Tumor and adjacent normal tissue FFPE blocks").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Post mortem tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "H&E slide, tumor and adjacent normal tissue FFPE").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Bone marrow").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Cord blood").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Normal TMA block").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "H&E Slide, normal tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "H&E Slide, tumor tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "H&E Slide, tumor and adjacent normal tissue sample FFPE").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Synovial fluid").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Bone").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Cell lines").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: RBC pellet").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Serum, blood clot from tube").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Protein lysate").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Circulating tumor cells (CTC)").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Cell free DNA").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Buffy coat, clot from tube").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: IPS cells").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Skin biopsy for fibroblast culture").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Whole blood for EBV Lymphoblast culture").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Tumor and adjacent normal TMA blocks").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Skin").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Tissue for DNA").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: DNA, saliva").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: WBC from peripheral blood/bone marrow").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Erythrocytes").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Blood clot").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Feces").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Maygrunwald giemsa stained bone marrow smears").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Image of H&E Slide, tumor and adjacent normal tissue sample FFPE").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Lymphblast cell lines").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Lymphocytes").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Formalin fixed placental tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: RNA later preserved placental punches").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Snap frozen placental tissue").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Cervical/Vaginal/Rectal swabs (multiomics)").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: CBMC's").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Hair").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Nail").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Nerve").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Muscle").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Stem cells").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Lymphoblastic cell lines").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Fibroblast cell lines").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: microRNA, CSF").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: unstained BM smears").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: DNA, saliva").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Not specified").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: LCL generated cell lines from PMBC's").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Established cell lines, custom").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Cervical cell samples").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Library").save(flush:true, failOnError:true)
    svy = new SurveyProductType(name: "Other: Dried blood spots").save(flush:true, failOnError:true)


    //SurveyEquipmentType
		println "Surveydata.groovy: SurveyEquipmentType"		
    def seq = new SurveyEquipmentType(name: "Centrifuge, refrigerated, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Centrifuge, refrigerated, stand-alone").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated nucleic acid/protein extraction instrument").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Bulk label printer, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Large cryogenic aluminum Dewar's").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 20°C to minus 40°C Refrigerator").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 80°C Manual chest freezer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 20°C to minus 148°C LN² Cryotank").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Microscope").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "PCR thermal cycler").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Orbital bath shaker, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Robotic frozen specimen aliquotter, large").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Incubator, automated").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Sample/tube picking & sorting station, stand-alone").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated sample capper-de-capper, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Tube puncher and selecting module, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 20°C Automated biostore").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Safety cabinet").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 80°C Manual vertical freezer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated blood fractionation system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Real time PCR System").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Laboratory workbench").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Manual tissue microarray (TMA) instrument").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Dry vapor shippers, large").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Protective shipping carton, industrial").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 149°C to minus 190°C LN² Cryotank").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Cold table/cryogenic workbench").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Bar-code flat scanner, multi-tray").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Cryo-cart").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Mass spectrometer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Laminar flow cabinet/hood").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Cryostat").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Laser capture microdissection system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: TMA platform (automated)/virtual microscopy").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Flow cytometer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Microtome").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Gene array scanner workstation").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "DNA/RNA sequencing system/analyzer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Autoclave").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Tissue embedding station").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated tissue microarray (TMA) instrument").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Slide autostainer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated tissue cassette labeler, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Cold room/walk-in").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Western blot transfer system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Controlled rate freezer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Incubator, manual").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "High through-put screening instrument").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Digital slide imager").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Biosafey cabinet").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Incubator").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Thermocycler").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Refrigerated centrifuge").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Automated DNA extraction station").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated straw filling station, stand-alone").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Clean room").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "SPIN tissue processor, microwave").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Blot hybridization system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Reagent dispenser").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Sample/tube picking & sorting station, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Tissue processor, walk away").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Automated cell counter").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Bulk sample labeler, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated sample/vial filling station, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Plasmid processing station").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Biosafey cabinet Level II").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Weighing scale").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Cryocart").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Large block and slide storage firesafe").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated sample/vial filling station, stand-alone").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Basic electrophoresis equipment").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Molecular device plate spectrophotometer/luminometer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Nanodrop").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Real time PCR machine").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Cell counter").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Vortex").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Spectrophotometer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Bioanalyzer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated microplate washer, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Pipettors").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Pipette aids").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: RiOs water filtration system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Balance").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Water bath").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Mobile Cryo-tank rack lift system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Refrigerator").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Cart").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Slide drawer filing system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Agarose gel electrophoresis system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Gel documentation system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 148°C Manual vertical freezer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Spectrophotomer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Analytical balance").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "RFID Flat scanner, multi-tray").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Sample volume, tube/plate auditor checking station, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Sample volume, tube/plate auditor checking station, stand-alone").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Transmission electron microscope").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Nucleic acid integrity analyzer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Liquid handler").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "minus 148°C Manual chest freezer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Scale").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Waterbath/Coldbath").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Refrigerator minus 0°C to minus 9°C").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Linear bar-code scanner").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: 2200 TapeStation").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Temperature monitor probes").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: PCR Workstation").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Cytospin").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Cool cell").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Freezer monitoring system").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Inventory database").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Tissue processor, rapid conventional").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Not specified").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Cryogenic cabinet freezer").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated stem cell culture instrument").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Automated microplate dispenser/sample processor, bench-top").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: Flatbed plate scanner").save(flush:true, failOnError:true)
    seq = new SurveyEquipmentType(name: "Other: DNA/RNA spectral analyzer").save(flush:true, failOnError:true)    


    //SurveySpendItems (time)
    println "Surveydata.groovy: SurveySpendItems"		
    svy = new SurveySpendItem(name: "Specimen and service provision", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Building Biobank inventory (specimens and/or data)", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Quality management and proficiency testing", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Facility operations and maintenance", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Administrative time", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Specimen and service provision", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Biobank promotion, marketing and/or business development", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Providing external education and training services", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Other: Not specified", type: "time").save(flush:true, failOnError:true)
    svy = new SurveySpendItem(name: "Other: Governance", type: "time").save(flush:true, failOnError:true)		

	//SurveyLaborSalaryRange 
	println "Surveydata.groovy: SurveyLaborSalaryRange"		
    def slsr = new SurveyLaborSalaryRange(name:"\$0", copyable:0).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"<\$5,000", copyable:2500.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$5,001-\$9,999", copyable:7500.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$10,000-\$19,999", copyable:15000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$20,000-\$39,999", copyable:30000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$40,000-\$59,999", copyable:50000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$60,000-\$79,999", copyable:70000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$80,000-\$99,999", copyable:90000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"\$100,000-\$250,000", copyable:175000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"> \$250,000", copyable:250000.00).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"not reported", copyable:0).save(flush:true, failOnError:true)
    slsr = new SurveyLaborSalaryRange(name:"not applicable", copyable:0).save(flush:true, failOnError:true)
  
    //SurveyLaborType
    println "Surveydata.groovy: SurveyLaborType"		
		def datapoint = new SurveyLaborType(name:"Clinical Research associate").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"General manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Lab technician").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Repository manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Lab manager/supervisor").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Business manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Histotechnician").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Data Manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Research assistant").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Administrative/Executive assistant").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Repository coordinator").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Head/Group/Team leader").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Program/Project manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Quality manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Associate/Scientific director").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Bioinformatics professional").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Technical/Executive director").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Clinical Research Coordinator").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Pathologist").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Pathology Assistant").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Research/Study nurse").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Individual researcher/scientist").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Clinical resident/fellow").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Chief operating officer (COO)").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Chief Technology officer (CTO)").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Molecular biologist").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Molecular biologist").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Customer product/service representative").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Facility director").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Assistant technician").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Chief scientific officer (CSO)/Site PI's").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Sample manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Bioethics consultant").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Biostatistician").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other-Lab assistant").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Genetic counselor, Sr.").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Quality program coordinator").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Research lab assistant").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Deputy technical coordinator").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Chief Financial officer (CFO)").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Chief Commercial officer (COO)").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Product manager").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Advisor").save(flush:true, failOnError:true)
		datapoint = new SurveyLaborType(name:"Other: Programmer").save(flush:true, failOnError:true)


    //SurveyLaborType
    println "Surveydata.groovy: SurveyLaborFringeRate"		    
		datapoint = new SurveyLaborFringeRate(name:"<10%", copyable: 5).save(flush:true, failOnError:true)
		datapoint = new SurveyLaborFringeRate(name:"11%-20%", copyable:15).save(flush:true, failOnError:true)
		datapoint = new SurveyLaborFringeRate(name:"21%-30%", copyable:25).save(flush:true, failOnError:true)
		datapoint = new SurveyLaborFringeRate(name:"41%-50%", copyable:45).save(flush:true, failOnError:true)
		datapoint = new SurveyLaborFringeRate(name:"31%-40%", copyable:35).save(flush:true, failOnError:true)
		datapoint = new SurveyLaborFringeRate(name:"> 50%", copyable:50).save(flush:true, failOnError:true)
        datapoint = new SurveyLaborFringeRate(name:"not reported", copyable:0).save(flush:true, failOnError:true)

    //SurveyEquipmentBuyLease
    println "Surveydata.groovy: SurveyEquipmentBuyLease"		    
		datapoint = new SurveyEquipmentBuyLease(name:"Buy").save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentBuyLease(name:"Lease").save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentBuyLease(name:"Other: Not specified").save(flush:true, failOnError:true)
        datapoint = new SurveyEquipmentBuyLease(name:"not reported").save(flush:true, failOnError:true)

		SurveyEquipmentAnnual
    println "Surveydata.groovy: SurveyEquipmentAnnual"		    
		datapoint = new SurveyEquipmentAnnual(name:"<\$999", copyable:500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$1,000-\$1,999", copyable:1500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$50,000-\$59,999", copyable:55000.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$25,000-\$27,499", copyable:26250.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$20,000-\$22,499", copyable:21250.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$40,000-\$49,999", copyable:45000.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$9,000-\$9,999", copyable:9500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$3,000-\$3,999", copyable:3500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$2,000-\$2,999", copyable:2500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$6,000-\$6,999", copyable:6500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$10,000-\$12,499", copyable:11250.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$28,000-\$30,999", copyable:31000.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$5,000-\$5,999", copyable:5500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$31,000-\$39,999", copyable:35500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$4,000-\$4,999", copyable:4500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$8,000-\$8,999", copyable:8500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$7,000-\$7,999", copyable:7500.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$12,500-\$14,999", copyable:13750.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$15,000-\$17,499", copyable:16250.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$23,000-\$24,999", copyable:24000.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"\$200,000-\$249,000", copyable:225000.00).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentAnnual(name:"not reported", copyable:0).save(flush:true, failOnError:true)
        datapoint = new SurveyEquipmentAnnual(name:"not applicable", copyable:0).save(flush:true, failOnError:true)

		SurveyEquipmentPrice
    println "Surveydata.groovy: SurveyEquipmentPrice"		    
		datapoint = new SurveyEquipmentPrice(name:"\$4,000-\$4,999", copyable:4500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$7,000-\$7,999", copyable:7500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$10,000-\$19,999", copyable:15000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$1,000-\$1,999", copyable:1500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$1-\$999", copyable:500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$9,000-\$9,999", copyable:9500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$3,000-\$3,999", copyable:3500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$2,000-\$2,999", copyable:2500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$250,000-\$499,999", copyable:375000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$5,000-\$5,999", copyable:5500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$20,000-\$29,999", copyable:25000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:">\$500,000", copyable:500000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$200,000-\$249,999", copyable:225000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$40,000-\$49,999", copyable:45000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$0", copyable:0).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$6,000-\$6,999", copyable:6500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$70,000-\$79,999", copyable:75000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$30,000-\$39,999", copyable:35000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$50,000-\$59,999", copyable:55000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$8,000-\$8,999", copyable:8500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$60,000-\$69,999", copyable:65000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$11,000-\$19,999", copyable:15500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$125,000-\$149,999", copyable:137500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$150,000-\$174,999", copyable:162500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$80,000-\$89,999", copyable:85000).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$100,000-\$124,999", copyable:112500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"\$175,000-\$199,999", copyable:187500).save(flush:true, failOnError:true)
		datapoint = new SurveyEquipmentPrice(name:"not reported", copyable:0).save(flush:true, failOnError:true)
        datapoint = new SurveyEquipmentPrice(name:"not applicable", copyable:0).save(flush:true, failOnError:true)

    println "Surveydata.groovy: enumeration data complete"
		println "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

	}

}