drop table bemtuser cascade constraints;
drop table costplus_allocated cascade constraints;
drop table costplus_cogs cascade constraints;
drop table costplus_other cascade constraints;
drop table disclaimer cascade constraints;
drop table encrypted_data cascade constraints;
drop table equipment cascade constraints;
drop table equipment_type cascade constraints;
drop table labor cascade constraints;
drop table labor_type cascade constraints;
drop table organization cascade constraints;
drop table product cascade constraints;
drop table product_type cascade constraints;
drop table proforma cascade constraints;
drop table proforma_expense cascade constraints;
drop table proforma_expense_type cascade constraints;
drop table proforma_project_cogs cascade constraints;
drop table proforma_project_revenue cascade constraints;
drop table proformaequipmentforecast cascade constraints;
drop table proformalaborforecast cascade constraints;
drop table proformaproduct cascade constraints;
drop table proformaproductforecast cascade constraints;
drop table proformaproject cascade constraints;
drop table project cascade constraints;
drop table project_fee_schedule cascade constraints;
drop table project_product cascade constraints;
drop table sample cascade constraints;
drop table snapshot cascade constraints;
drop table snapshot_equipment cascade constraints;
drop table snapshot_equipment_forecast cascade constraints;
drop table snapshot_expense cascade constraints;
drop table snapshot_labor cascade constraints;
drop table snapshot_labor_forecast cascade constraints;
drop table snapshot_product cascade constraints;
drop table snapshot_product_forecast cascade constraints;
drop table snapshot_project cascade constraints;
drop table speciman_service_type cascade constraints;
drop table supply cascade constraints;
drop table supply_default cascade constraints;
drop table supply_type cascade constraints;
drop table survey cascade constraints;
drop table survey_country cascade constraints;
drop table survey_equipment cascade constraints;
drop table survey_equipment_annual cascade constraints;
drop table survey_equipment_buy_lease cascade constraints;
drop table survey_equipment_price cascade constraints;
drop table survey_equipment_type cascade constraints;
drop table survey_exp_recovery cascade constraints;
drop table survey_facility cascade constraints;
drop table survey_geo_area cascade constraints;
drop table survey_institution_type cascade constraints;
drop table survey_labor cascade constraints;
drop table survey_labor_fringe_rate cascade constraints;
drop table survey_labor_salary_range cascade constraints;
drop table survey_labor_type cascade constraints;
drop table survey_operating_model cascade constraints;
drop table survey_product cascade constraints;
drop table survey_product_type cascade constraints;
drop table survey_service cascade constraints;
drop table survey_service_type cascade constraints;
drop table survey_spend cascade constraints;
drop table survey_spend_item cascade constraints;
drop sequence hibernate_sequence;
create table bemtuser (id number(19,0) not null, version number(19,0) not null, email varchar2(255 char) not null unique, name_first varchar2(20 char) not null, name_last varchar2(20 char) not null, password varchar2(255 char) not null, primary key (id));
create table costplus_allocated (id number(19,0) not null, version number(19,0) not null, cost number(19,2) not null, equipment_id number(19,0), labor_id number(19,0), organization_id number(19,0) not null, product_id number(19,0) not null, quantity number(10,0) not null, primary key (id));
create table costplus_cogs (id number(19,0) not null, version number(19,0) not null, cost number(19,2) not null, organization_id number(19,0) not null, product_id number(19,0) not null, quantity number(19,2) not null, supply_id number(19,0) not null, type varchar2(255 char) not null, primary key (id));
create table costplus_other (id number(19,0) not null, version number(19,0) not null, cost number(19,2) not null, organization_id number(19,0) not null, other varchar2(255 char) not null, product_id number(19,0) not null, primary key (id));
create table disclaimer (id number(19,0) not null, version number(19,0) not null, description varchar2(1000 char) not null, fee_id number(19,0) not null, primary key (id));
create table encrypted_data (id varchar2(32 char) not null, version number(19,0) not null, data_item varchar2(512 char) not null, primary key (id));
create table equipment (id number(19,0) not null, version number(19,0) not null, annual_billable_hours number(10,0) not null, annual_service_contract number(10,0) not null, cost number(10,0) not null, equip_id number(19,0) not null, name varchar2(255 char) not null, organization_id number(19,0) not null, type varchar2(9 char) not null, usable_life number(10,0) not null, primary key (id));
create table equipment_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, parent_id number(19,0), primary key (id));
create table labor (id number(19,0) not null, version number(19,0) not null, annual_salary number(10,0) not null, benefit_percent number(10,0) not null, category_id number(19,0) not null, name varchar2(255 char) not null, organization_id number(19,0) not null, primary key (id));
create table labor_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, parent_id number(19,0), primary key (id));
create table organization (id number(19,0) not null, version number(19,0) not null, deleted number(1,0) not null, description varchar2(1000 char) not null, name varchar2(255 char) not null, owner_id number(19,0), template number(1,0) not null, primary key (id));
create table product (id number(19,0) not null, version number(19,0) not null, cost number(19,2), description varchar2(1000 char) not null, indirect number(19,2) not null, indirect_percent double precision not null, name varchar2(255 char) not null, organization_id number(19,0) not null, subtype_id number(19,0) not null, type_id number(19,0) not null, unit_cost number(19,2), primary key (id));
create table product_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, parent_id number(19,0), primary key (id));
create table proforma (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, organization_id number(19,0) not null, primary key (id));
create table proforma_expense (id number(19,0) not null, version number(19,0) not null, description varchar2(255 char), expense_id number(19,0) not null, proforma_id number(19,0) not null, year1 number(19,2) not null, year2 number(19,2) not null, year3 number(19,2) not null, primary key (id));
create table proforma_expense_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, sequence number(10,0) not null, primary key (id));
create table proforma_project_cogs (id number(19,0) not null, version number(19,0) not null, description varchar2(255 char), name varchar2(255 char) not null, proformaproject_id number(19,0) not null, year1 number(19,2) not null, year2 number(19,2) not null, year3 number(19,2) not null, primary key (id));
create table proforma_project_revenue (id number(19,0) not null, version number(19,0) not null, description varchar2(255 char), name varchar2(255 char) not null, proformaproject_id number(19,0) not null, year1 number(19,2) not null, year2 number(19,2) not null, year3 number(19,2) not null, primary key (id));
create table proformaequipmentforecast (id number(19,0) not null, version number(19,0) not null, added number(10,0) not null, equipment_id number(19,0) not null, period number(10,0) not null, proforma_id number(19,0) not null, quantity number(10,0) not null, primary key (id));
create table proformalaborforecast (id number(19,0) not null, version number(19,0) not null, labor_id number(19,0) not null, period number(10,0) not null, proforma_id number(19,0) not null, quantity number(19,2) not null, primary key (id));
create table proformaproduct (id number(19,0) not null, version number(19,0) not null, cost1 number(19,2) not null, cost2 number(19,2) not null, cost3 number(19,2) not null, cost_change2 double precision not null, cost_change3 double precision not null, price1 number(19,2) not null, price2 number(19,2) not null, price3 number(19,2) not null, price_change2 double precision not null, price_change3 double precision not null, product_id number(19,0) not null, project_id number(19,0) not null, primary key (id));
create table proformaproductforecast (id number(19,0) not null, version number(19,0) not null, period number(10,0) not null, product_id number(19,0) not null, quantity number(10,0) not null, primary key (id));
create table proformaproject (id number(19,0) not null, version number(19,0) not null, cost1 number(19,2) default 0.00 not null, cost2 number(19,2) default 0.00 not null, cost3 number(19,2) default 0.00 not null, proforma_id number(19,0) not null, project_id number(19,0) not null, rev1 number(19,2) default 0.00 not null, rev2 number(19,2) default 0.00 not null, rev3 number(19,2) default 0.00 not null, primary key (id));
create table project (id number(19,0) not null, version number(19,0) not null, description varchar2(1000 char) not null, fee_id number(19,0), name varchar2(100 char) not null, organization_id number(19,0) not null, primary key (id));
create table project_fee_schedule (id number(19,0) not null, version number(19,0) not null, description varchar2(1000 char) not null, name varchar2(100 char) not null, primary key (id));
create table project_product (id number(19,0) not null, version number(19,0) not null, base_price number(19,2), product_id number(19,0) not null, project_id number(19,0) not null, recovery_percent double precision, primary key (id));
create table sample (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, type_id number(19,0) not null, primary key (id));
create table snapshot (id number(19,0) not null, version number(19,0) not null, created timestamp not null, description varchar2(255 char) not null, name varchar2(255 char) not null, organization_id number(19,0) not null, primary key (id));
create table snapshot_equipment (id number(19,0) not null, version number(19,0) not null, annual_billable_hours number(10,0) not null, annual_service_contract number(10,0) not null, cost number(10,0) not null, equipment varchar2(255 char) not null, name varchar2(255 char) not null, snapshot_id number(19,0) not null, type varchar2(9 char) not null, usable_life number(10,0) not null, year1 number(19,2) not null, year2 number(19,2) not null, year3 number(19,2) not null, primary key (id));
create table snapshot_equipment_forecast (id number(19,0) not null, version number(19,0) not null, added number(10,0) not null, equipment_id number(19,0) not null, period number(10,0) not null, quantity number(10,0) not null, primary key (id));
create table snapshot_expense (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, sequence number(10,0) not null, snapshot_id number(19,0) not null, year1 number(19,2) not null, year2 number(19,2) not null, year3 number(19,2) not null, primary key (id));
create table snapshot_labor (id number(19,0) not null, version number(19,0) not null, annual_salary number(10,0) not null, benefit_percent number(10,0) not null, name varchar2(255 char) not null, snapshot_id number(19,0) not null, type varchar2(255 char) not null, year1 number(19,2) not null, year2 number(19,2) not null, year3 number(19,2) not null, primary key (id));
create table snapshot_labor_forecast (id number(19,0) not null, version number(19,0) not null, labor_id number(19,0) not null, period number(10,0) not null, quantity number(19,2) not null, primary key (id));
create table snapshot_product (id number(19,0) not null, version number(19,0) not null, cogs1 number(19,2) not null, cogs2 number(19,2) not null, cogs3 number(19,2) not null, cost1 number(19,2) not null, cost2 number(19,2) not null, cost3 number(19,2) not null, cost_change2 double precision not null, cost_change3 double precision not null, name varchar2(255 char) not null, price1 number(19,2) not null, price2 number(19,2) not null, price3 number(19,2) not null, price_change2 double precision not null, price_change3 double precision not null, project_id number(19,0) not null, rev1 number(19,2) not null, rev2 number(19,2) not null, rev3 number(19,2) not null, primary key (id));
create table snapshot_product_forecast (id number(19,0) not null, version number(19,0) not null, cost number(19,2) not null, period number(10,0) not null, price number(19,2) not null, product_id number(19,0) not null, quantity number(10,0) not null, primary key (id));
create table snapshot_project (id number(19,0) not null, version number(19,0) not null, cogs1 number(19,2), cogs2 number(19,2), cogs3 number(19,2), name varchar2(255 char) not null, rev1 number(19,2), rev2 number(19,2), rev3 number(19,2), snapshot_id number(19,0) not null, primary key (id));
create table speciman_service_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, parent_id number(19,0), type_id number(19,0) not null, primary key (id));
create table supply (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, organization_id number(19,0) not null, othertype varchar2(255 char), type_id number(19,0) not null, unit_price number(19,2) not null, units varchar2(255 char) not null, primary key (id));
create table supply_default (id number(19,0) not null, version number(19,0) not null, annual_billable_hours number(10,0) not null, annualized_cost number(19,2) not null, name varchar2(255 char) not null, unit_price number(19,2) not null, units varchar2(255 char) not null, primary key (id));
create table supply_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, parent_id number(19,0), primary key (id));
create table survey (id number(19,0) not null, version number(19,0) not null, age double precision not null, complete number(1,0) not null, cost_recovery varchar2(255 char) not null, country_id number(19,0) not null, exp_recovery_id number(19,0) not null, facility_id number(19,0) not null, geo_id number(19,0) not null, indirect_rate double precision not null, inst_id number(19,0) not null, international varchar2(255 char) not null, markup_service double precision not null, markup_specimen double precision not null, model_id number(19,0) not null, operating_budget number(19,2), sites number(10,0) not null, source_id varchar2(255 char) not null, startup_spend number(19,2), survey_year number(10,0) not null, primary key (id));
create table survey_country (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_equipment (id number(19,0) not null, version number(19,0) not null, buy_id number(19,0) not null, contract_id number(19,0) not null, life varchar2(255 char) not null, price_id number(19,0) not null, survey_id number(19,0) not null, type_id number(19,0) not null, units varchar2(255 char) not null, primary key (id));
create table survey_equipment_annual (id number(19,0) not null, version number(19,0) not null, copyable number(10,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_equipment_buy_lease (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_equipment_price (id number(19,0) not null, version number(19,0) not null, copyable number(10,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_equipment_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_exp_recovery (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_facility (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_geo_area (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_institution_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_labor (id number(19,0) not null, version number(19,0) not null, fringe_id number(19,0) not null, fte varchar2(255 char) not null, range_id number(19,0) not null, survey_id number(19,0) not null, type_id number(19,0) not null, primary key (id));
create table survey_labor_fringe_rate (id number(19,0) not null, version number(19,0) not null, copyable number(10,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_labor_salary_range (id number(19,0) not null, version number(19,0) not null, copyable number(19,2) not null, name varchar2(255 char) not null, primary key (id));
create table survey_labor_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_operating_model (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_product (id number(19,0) not null, version number(19,0) not null, collection_vol varchar2(255 char) not null, data_collected varchar2(255 char) not null, dist_vol varchar2(255 char) not null, ischemic_time varchar2(255 char) not null, preservation varchar2(255 char) not null, price varchar2(255 char) not null, stabilization varchar2(255 char) not null, survey_id number(19,0) not null, type_id number(19,0) not null, weight varchar2(255 char) not null, primary key (id));
create table survey_product_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_service (id number(19,0) not null, version number(19,0) not null, price varchar2(255 char) not null, survey_id number(19,0) not null, type varchar2(255 char) not null, primary key (id));
create table survey_service_type (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, primary key (id));
create table survey_spend (id number(19,0) not null, version number(19,0) not null, item_id number(19,0) not null, spend_dollar number(19,2) not null, spend_percent double precision not null, survey_id number(19,0) not null, primary key (id));
create table survey_spend_item (id number(19,0) not null, version number(19,0) not null, name varchar2(255 char) not null, type varchar2(255 char) not null, primary key (id));
alter table costplus_allocated add constraint FK9D9A2D6FC5FBD9C0 foreign key (organization_id) references organization;
alter table costplus_allocated add constraint FK9D9A2D6F80528194 foreign key (labor_id) references labor;
alter table costplus_allocated add constraint FK9D9A2D6F4B809FD4 foreign key (equipment_id) references equipment;
alter table costplus_allocated add constraint FK9D9A2D6F569DC6B4 foreign key (product_id) references product;
alter table costplus_cogs add constraint FKCE8510B0C5FBD9C0 foreign key (organization_id) references organization;
alter table costplus_cogs add constraint FKCE8510B0569DC6B4 foreign key (product_id) references product;
alter table costplus_cogs add constraint FKCE8510B0A88994C0 foreign key (supply_id) references supply;
alter table costplus_other add constraint FK2C867B8C5FBD9C0 foreign key (organization_id) references organization;
alter table costplus_other add constraint FK2C867B8569DC6B4 foreign key (product_id) references product;
alter table disclaimer add constraint FK19C5759B3029C43E foreign key (fee_id) references project_fee_schedule;
alter table equipment add constraint FK4027E58EC5FBD9C0 foreign key (organization_id) references organization;
alter table equipment add constraint FK4027E58E7EE5114C foreign key (equip_id) references equipment_type;
alter table equipment_type add constraint FK7DC0AB4BD731E692 foreign key (parent_id) references equipment_type;
alter table labor add constraint FK61F8030C5FBD9C0 foreign key (organization_id) references organization;
alter table labor add constraint FK61F803071595860 foreign key (category_id) references labor_type;
alter table labor_type add constraint FKB8EA65E991175D34 foreign key (parent_id) references labor_type;
alter table organization add constraint FK4644ED33D896B602 foreign key (owner_id) references bemtuser;
alter table product add constraint FKED8DCCEFC5FBD9C0 foreign key (organization_id) references organization;
alter table product add constraint FKED8DCCEFCC9ECFBD foreign key (subtype_id) references speciman_service_type;
alter table product add constraint FKED8DCCEF8E969363 foreign key (type_id) references product_type;
alter table product_type add constraint FK3C79388A3CD663F3 foreign key (parent_id) references product_type;
alter table proforma add constraint FKC4457D90C5FBD9C0 foreign key (organization_id) references organization;
alter table proforma_expense add constraint FKBE7B5CA9FBF692BE foreign key (expense_id) references proforma_expense_type;
alter table proforma_expense add constraint FKBE7B5CA928C883A0 foreign key (proforma_id) references proforma;
alter table proforma_project_cogs add constraint FK26A79A0D79C70E74 foreign key (proformaproject_id) references proformaproject;
alter table proforma_project_revenue add constraint FK533BC04779C70E74 foreign key (proformaproject_id) references proformaproject;
alter table proformaequipmentforecast add constraint FK360D95F94B809FD4 foreign key (equipment_id) references equipment;
alter table proformaequipmentforecast add constraint FK360D95F928C883A0 foreign key (proforma_id) references proforma;
alter table proformalaborforecast add constraint FK355269B80528194 foreign key (labor_id) references labor;
alter table proformalaborforecast add constraint FK355269B28C883A0 foreign key (proforma_id) references proforma;
alter table proformaproduct add constraint FK233AED5F1BD544E4 foreign key (project_id) references proformaproject;
alter table proformaproduct add constraint FK233AED5F569DC6B4 foreign key (product_id) references product;
alter table proformaproductforecast add constraint FKC534E85AF9BAED24 foreign key (product_id) references proformaproduct;
alter table proformaproject add constraint FK233D6B8978B81E74 foreign key (project_id) references project;
alter table proformaproject add constraint FK233D6B8928C883A0 foreign key (proforma_id) references proforma;
alter table project add constraint FKED904B19C5FBD9C0 foreign key (organization_id) references organization;
alter table project add constraint FKED904B193029C43E foreign key (fee_id) references project_fee_schedule;
alter table project_product add constraint FK5EE195C978B81E74 foreign key (project_id) references project;
alter table project_product add constraint FK5EE195C9569DC6B4 foreign key (product_id) references product;
alter table sample add constraint FKC9C775AA8E969363 foreign key (type_id) references product_type;
alter table snapshot add constraint FK10FAD5C4C5FBD9C0 foreign key (organization_id) references organization;
alter table snapshot_equipment add constraint FKCFB650D318C12720 foreign key (snapshot_id) references snapshot;
alter table snapshot_equipment_forecast add constraint FKEA22E7E72018AC70 foreign key (equipment_id) references snapshot_equipment;
alter table snapshot_expense add constraint FK2A3F40DD18C12720 foreign key (snapshot_id) references snapshot;
alter table snapshot_labor add constraint FKA54855F518C12720 foreign key (snapshot_id) references snapshot;
alter table snapshot_labor_forecast add constraint FK19C78905B6413C30 foreign key (labor_id) references snapshot_labor;
alter table snapshot_product add constraint FK65D84574EDE2A210 foreign key (project_id) references snapshot_project;
alter table snapshot_product_forecast add constraint FK4B239866CBC84A50 foreign key (product_id) references snapshot_product;
alter table snapshot_project add constraint FK65DAC39E18C12720 foreign key (snapshot_id) references snapshot;
alter table speciman_service_type add constraint FKFA7455578E969363 foreign key (type_id) references product_type;
alter table speciman_service_type add constraint FKFA7455573666E68D foreign key (parent_id) references speciman_service_type;
alter table supply add constraint FKCAE2A8EFC5FBD9C0 foreign key (organization_id) references organization;
alter table supply add constraint FKCAE2A8EF8BD8D76F foreign key (type_id) references supply_type;
alter table supply_type add constraint FKFDCDDC8A3A18A7FF foreign key (parent_id) references supply_type;
alter table survey add constraint FKCAE3A75A2D80FED5 foreign key (exp_recovery_id) references survey_exp_recovery;
alter table survey add constraint FKCAE3A75A2146B367 foreign key (geo_id) references survey_geo_area;
alter table survey add constraint FKCAE3A75ADC12A5E6 foreign key (inst_id) references survey_institution_type;
alter table survey add constraint FKCAE3A75A6CFBDD1A foreign key (country_id) references survey_country;
alter table survey add constraint FKCAE3A75A9E3693BA foreign key (facility_id) references survey_facility;
alter table survey add constraint FKCAE3A75A29803139 foreign key (model_id) references survey_operating_model;
alter table survey_equipment add constraint FK3B8E9EE91C6D150C foreign key (price_id) references survey_equipment_price;
alter table survey_equipment add constraint FK3B8E9EE957854B95 foreign key (contract_id) references survey_equipment_annual;
alter table survey_equipment add constraint FK3B8E9EE942862FB6 foreign key (buy_id) references survey_equipment_buy_lease;
alter table survey_equipment add constraint FK3B8E9EE91C3178E0 foreign key (survey_id) references survey;
alter table survey_equipment add constraint FK3B8E9EE96D3E1548 foreign key (type_id) references survey_equipment_type;
alter table survey_labor add constraint FK46771F0BCEB17380 foreign key (range_id) references survey_labor_salary_range;
alter table survey_labor add constraint FK46771F0B1C3178E0 foreign key (survey_id) references survey;
alter table survey_labor add constraint FK46771F0B2EE21EEA foreign key (type_id) references survey_labor_type;
alter table survey_labor add constraint FK46771F0BE6C6504A foreign key (fringe_id) references survey_labor_fringe_rate;
alter table survey_product add constraint FK7679210A1C3178E0 foreign key (survey_id) references survey;
alter table survey_product add constraint FK7679210A245AC29 foreign key (type_id) references survey_product_type;
alter table survey_service add constraint FKFF2F1AD01C3178E0 foreign key (survey_id) references survey;
alter table survey_spend add constraint FK46E0A039A0221E78 foreign key (item_id) references survey_spend_item;
alter table survey_spend add constraint FK46E0A0391C3178E0 foreign key (survey_id) references survey;
create sequence hibernate_sequence;
